name: scratchpad

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - NoImplicitPrelude
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NegativeLiterals
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData # NOTE: that this is on.
  - TupleSections
  - TypeApplications
  - TypeOperators

ghc-options: -Wall
dependencies:

  # Notable

  - main-tester
  - megaparsec
  - parser-combinators

  # Other

  - aeson
  - async
  - base
  - bytestring
  - containers
  - directory
  - filepath
  - hashable
  - lens
  - mtl
  - optparse-applicative
  - profunctors
  - random
  - safe-exceptions
  - stm
  - text
  - time
  - transformers
  - unliftio
  - unordered-containers

tests:
  spec:
    source-dirs: .
    main: Spec.hs
    dependencies:
      - hspec
      - QuickCheck
